# ruff: noqa
"""Local smoke test for the standard weekly scaffold."""

from __future__ import annotations

from pathlib import Path


def test_week_scaffold_smoke() -> None:
    week_root = Path(__file__).resolve().parents[1]
    for relative in [
        "README.md",
        "WORKSHOP.md",
        "DATA_GUIDE.md",
        "BEGINNER_FORECASTING.md",
        "US_BEGINNER_FORECASTING.md",
        "APP_LAB.md",
        "APP_AUDIT.md",
        "SUBMISSION_CHECKLIST.md",
        "AGENTS.md",
        "guidance/week-context.md",
        "guidance/data-context.md",
        "guidance/output-context.md",
        "scripts/run_week.py",
        "scripts/describe_data.py",
        "scripts/describe_forecast_data.py",
        "scripts/make_beginner_forecasting_series.py",
        "scripts/run_beginner_unit_root_check.py",
        "scripts/run_beginner_naive_forecast.py",
        "scripts/run_beginner_ar_forecast.py",
        "scripts/run_beginner_arma_forecast.py",
        "scripts/run_beginner_arx_forecast.py",
        "scripts/run_beginner_armax_forecast.py",
        "scripts/run_beginner_ols_forecast.py",
        "scripts/run_beginner_enet_forecast.py",
        "scripts/run_beginner_model_horse_race.py",
        "scripts/run_beginner_ensemble_forecast.py",
        "scripts/make_beginner_forecast_story_figures.py",
        "scripts/make_us_beginner_forecasting_series.py",
        "scripts/run_us_beginner_unit_root_check.py",
        "scripts/run_us_beginner_naive_forecast.py",
        "scripts/run_us_beginner_ar_forecast.py",
        "scripts/run_us_beginner_arma_forecast.py",
        "scripts/run_us_beginner_arx_forecast.py",
        "scripts/run_us_beginner_model_horse_race.py",
        "scripts/make_us_beginner_forecast_story_figures.py",
        "scripts/build_forecast_inputs.py",
        "scripts/run_forecast_benchmarks.py",
        "data/README.md",
        "data/australia_macro_stage1_long.csv",
        "data/benchmark_leaderboard_fixture.csv",
        "scratch/README.md",
        "app/README.md",
        "app/streamlit_app.py",
        "app/app_config.py",
        "app/app_data.py",
        "app/app_insights.py",
        "app/app_views.py",
        "app/tests/test_app_smoke.py",
        "us_app/README.md",
        "us_app/streamlit_app.py",
        "us_app/app_config.py",
        "us_app/app_data.py",
        "us_app/app_insights.py",
        "us_app/app_views.py",
        "us_app/tests/test_app_smoke.py",
        "code/__init__.py",
        "code/beginner_forecasting.py",
        "code/forecast_story_figures.py",
        "code/forecast_specs.py",
        "code/forecast_data.py",
        "code/forecast_pipeline.py",
        "tests/test_beginner_forecasting.py",
    ]:
        assert (week_root / relative).exists(), relative

